/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIClasses;

import Helpers.ImageUtils;
import MainPackage.App;
import javax.swing.ImageIcon;
import javax.swing.JSlider;

/**
 *
 * @author author
 */
public class Home extends javax.swing.JFrame {
    
    private ImageUtils imageUtils = new ImageUtils();
    App app = App.getInstance();

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        ImageIcon imgIcon2 = imageUtils.loadScaledImage("/GUI/Assets/fightingSquare.png", 460, 850);
        ImageIcon cartoonNetworkLogo = imageUtils.loadScaledImage("/GUI/Assets/RegularShow/logo.png", 140, 80);
        ImageIcon nickelodeonLogo = imageUtils.loadScaledImage("/GUI/Assets/Avatar/logo.png", 140, 80);
        
        tvPanelUI1.getLogo().setIcon(cartoonNetworkLogo);
        tvPanelUI2.getLogo().setIcon(nickelodeonLogo);
        tvPanelUI1.getLogo().setText("");
        tvPanelUI2.getLogo().setText("");
        iaStatusLabel.setText("");
        WinnerLabelID.setText("");

        // Se setean las imagenes que la lucha en la IA.
//        ImageIcon regularShowCardIA=  imageUtils.loadScaledImage(app.getIaArena().getRegularShowFighter().getUrlSource(), 150, 200);
//        this.RegularShowCard.setIcon(regularShowCardIA);
//        ImageIcon avatarCardIA=  imageUtils.loadScaledImage(app.getIaArena().getAvatarFighter().getUrlSource(), 150, 200);
//        this.AvatarCard.setIcon(avatarCardIA);
        // Se configura el slider 
        battleDuration.setOpaque(false);
        battleDuration.setMinimum(1);
        battleDuration.setMaximum(20);
        battleDuration.setValue(App.getBattleDuration());
        
        this.fightingSquare.setIcon(imgIcon2);
        this.fightingSquare.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        battleDuration = new javax.swing.JSlider();
        WinnerLabelID = new javax.swing.JLabel();
        tvPanelUI1 = new GUIClasses.TvPanelUI();
        FightingTitle = new javax.swing.JLabel();
        tvPanelUI2 = new GUIClasses.TvPanelUI();
        avatarFighter = new GUIClasses.FighterUI();
        regularShowFighter = new GUIClasses.FighterUI();
        iaStatusLabel = new javax.swing.JLabel();
        Winner1 = new javax.swing.JLabel();
        roundLabel = new javax.swing.JLabel();
        fightingSquare = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(240, 233, 223));
        jPanel1.setMinimumSize(new java.awt.Dimension(1130, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        battleDuration.setForeground(new java.awt.Color(255, 255, 255));
        battleDuration.setMajorTickSpacing(9);
        battleDuration.setMaximum(20);
        battleDuration.setMinimum(1);
        battleDuration.setMinorTickSpacing(1);
        battleDuration.setPaintLabels(true);
        battleDuration.setPaintTicks(true);
        battleDuration.setValue(10);
        battleDuration.setOpaque(true);
        battleDuration.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                battleDurationStateChanged(evt);
            }
        });
        battleDuration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                battleDurationMouseClicked(evt);
            }
        });
        jPanel1.add(battleDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, -1, -1));

        WinnerLabelID.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        WinnerLabelID.setForeground(new java.awt.Color(255, 255, 255));
        WinnerLabelID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WinnerLabelID.setText("Ganador");
        jPanel1.add(WinnerLabelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 650, 370, -1));
        jPanel1.add(tvPanelUI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        FightingTitle.setFont(new java.awt.Font("Montserrat", 1, 36)); // NOI18N
        FightingTitle.setForeground(new java.awt.Color(255, 255, 255));
        FightingTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FightingTitle.setText("FIGHTING AREA");
        jPanel1.add(FightingTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 10, 390, -1));
        jPanel1.add(tvPanelUI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, -1, -1));
        jPanel1.add(avatarFighter, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, -1, 460));
        jPanel1.add(regularShowFighter, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, 460));

        iaStatusLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        iaStatusLabel.setForeground(new java.awt.Color(255, 255, 255));
        iaStatusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iaStatusLabel.setText("IA STATUS LABEL");
        jPanel1.add(iaStatusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 320, -1));

        Winner1.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        Winner1.setForeground(new java.awt.Color(255, 255, 255));
        Winner1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Winner1.setText("Ganador:");
        jPanel1.add(Winner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 630, 370, -1));

        roundLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        roundLabel.setForeground(new java.awt.Color(255, 255, 255));
        roundLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roundLabel.setText("Round: 0");
        jPanel1.add(roundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 320, -1));

        fightingSquare.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        fightingSquare.setForeground(new java.awt.Color(0, 0, 0));
        fightingSquare.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fightingSquare.setText("FIGHTING AREA backgound");
        jPanel1.add(fightingSquare, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, -80, 390, 830));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void battleDurationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_battleDurationMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_battleDurationMouseClicked

    private void battleDurationStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_battleDurationStateChanged
        // TODO add your handling code here:
        int newSpeed = getBattleDuration().getValue();
//        app.getIaArena().setCombatSpeed(newSpeed);
    }//GEN-LAST:event_battleDurationStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FightingTitle;
    private javax.swing.JLabel Winner1;
    private javax.swing.JLabel WinnerLabelID;
    private GUIClasses.FighterUI avatarFighter;
    private javax.swing.JSlider battleDuration;
    private javax.swing.JLabel fightingSquare;
    private javax.swing.JLabel iaStatusLabel;
    private javax.swing.JPanel jPanel1;
    private GUIClasses.FighterUI regularShowFighter;
    private javax.swing.JLabel roundLabel;
    private GUIClasses.TvPanelUI tvPanelUI1;
    private GUIClasses.TvPanelUI tvPanelUI2;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the tvPanelUI1
     */
    public GUIClasses.TvPanelUI getTvPanelUI1() {
        return tvPanelUI1;
    }

    /**
     * @return the tvPanelUI2
     */
    public GUIClasses.TvPanelUI getTvPanelUI2() {
        return tvPanelUI2;
    }

    /**
     * @return the avatarFighter
     */
    public GUIClasses.FighterUI getAvatarFighter() {
        return avatarFighter;
    }

    /**
     * @return the regularShowFighter
     */
    public GUIClasses.FighterUI getRegularShowFighter() {
        return regularShowFighter;
    }

    /**
     * @return the iaStatusLabel
     */
    public javax.swing.JLabel getIaStatusLabel() {
        return iaStatusLabel;
    }

    /**
     * @return the WinnerLabelID
     */
    public javax.swing.JLabel getWinnerLabelID() {
        return WinnerLabelID;
    }

    /**
     * @return the roundLabel
     */
    public javax.swing.JLabel getRoundLabel() {
        return roundLabel;
    }

    /**
     * @return the battleDuration
     */
    public javax.swing.JSlider getBattleDuration() {
        return battleDuration;
    }
}
