/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIClasses;

import Helpers.ImageUtils;
import MainPackage.App;
import java.util.HashSet;
import javax.swing.ImageIcon;
import javax.swing.JSlider;


/**
 *
 * @author author
 */
public class Home extends javax.swing.JFrame {

    private ImageUtils imageUtils = new ImageUtils();
    App app = App.getInstance();

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        ImageIcon imgIcon = imageUtils.loadScaledImage("/GUI/Assets/mordecai-yellow.png", 150, 200);
        ImageIcon imgIcon3 = imageUtils.loadScaledImage("/GUI/Assets/rigby-yellow.png", 150, 200);
        ImageIcon imgIcon4 = imageUtils.loadScaledImage("/GUI/Assets/rigby-yellow.png", 60, 80);
        ImageIcon imgIcon2 = imageUtils.loadScaledImage("/GUI/Assets/fightingSquare.png", 430, 700);
        
        //TODO: Quitar esto
        ImageIcon regularShowLogo = imageUtils.loadScaledImage("/GUI/Assets/regularShow.png", 140, 30);
        
        
        
        ImageIcon cartoonNetworkLogo = imageUtils.loadScaledImage("/GUI/Assets/CN.png", 140, 80);
        ImageIcon nickelodeonLogo = imageUtils.loadScaledImage("/GUI/Assets/nickelodeon.png", 140, 100);

        this.nickelodeonLogo.setIcon(nickelodeonLogo);
        this.cartoonNetworkLogo.setIcon(cartoonNetworkLogo);
        this.cartoonNetworkLogo.setText("");
        
        // Se setean las imagenes que la lucha en la IA.
        ImageIcon regularShowCardIA=  imageUtils.loadScaledImage(app.getIaArena().getRegularShowFighter().getUrlSource(), 150, 200);
        this.RegularShowCard.setIcon(regularShowCardIA);
       
        ImageIcon avatarCardIA=  imageUtils.loadScaledImage(app.getIaArena().getAvatarFighter().getUrlSource(), 150, 200);
        this.AvatarCard.setIcon(avatarCardIA);
        
        // Se configura el slider 
        jSlider1.setMinimum(300); 
        jSlider1.setMaximum(5000);
        jSlider1.setValue(app.getIaArena().getCombatSpeed());
        
        
      
        this.fightingSquare.setIcon(imgIcon2);
        
        
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSlider1 = new javax.swing.JSlider();
        AvatarCharacterID = new javax.swing.JLabel();
        RegularShowCharacterID1 = new javax.swing.JLabel();
        AvatarActualHP = new javax.swing.JLabel();
        RegularShowActualHP = new javax.swing.JLabel();
        Winner = new javax.swing.JLabel();
        RegularShowActualStatus = new javax.swing.JLabel();
        AvatarActualStatus = new javax.swing.JLabel();
        FightingTitle = new javax.swing.JLabel();
        RegularShowCard = new javax.swing.JLabel();
        AvatarCard = new javax.swing.JLabel();
        fightingSquare = new javax.swing.JLabel();
        fightingTitle4 = new javax.swing.JLabel();
        cartoonNetworkLogo = new javax.swing.JLabel();
        nickelodeonLogo = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(240, 233, 223));
        jPanel1.setMinimumSize(new java.awt.Dimension(1130, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSlider1.setMaximum(5000);
        jSlider1.setMinimum(300);
        jSlider1.setValue(3333);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        jSlider1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSlider1MouseClicked(evt);
            }
        });
        jPanel1.add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, -1, -1));

        AvatarCharacterID.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        AvatarCharacterID.setForeground(new java.awt.Color(255, 255, 255));
        AvatarCharacterID.setText("PersonajeID:");
        jPanel1.add(AvatarCharacterID, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, -1, -1));

        RegularShowCharacterID1.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        RegularShowCharacterID1.setForeground(new java.awt.Color(255, 255, 255));
        RegularShowCharacterID1.setText("PersonajeID:");
        jPanel1.add(RegularShowCharacterID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, -1, -1));

        AvatarActualHP.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        AvatarActualHP.setForeground(new java.awt.Color(255, 255, 255));
        AvatarActualHP.setText("HP actual:");
        jPanel1.add(AvatarActualHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 480, -1, -1));

        RegularShowActualHP.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        RegularShowActualHP.setForeground(new java.awt.Color(255, 255, 255));
        RegularShowActualHP.setText("HP actual:");
        jPanel1.add(RegularShowActualHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, -1, -1));

        Winner.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        Winner.setForeground(new java.awt.Color(255, 255, 255));
        Winner.setText("Ganador");
        jPanel1.add(Winner, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 630, -1, -1));

        RegularShowActualStatus.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        RegularShowActualStatus.setForeground(new java.awt.Color(255, 255, 255));
        RegularShowActualStatus.setText("Estado actual:");
        jPanel1.add(RegularShowActualStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 540, -1, -1));

        AvatarActualStatus.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        AvatarActualStatus.setForeground(new java.awt.Color(255, 255, 255));
        AvatarActualStatus.setText("Estado actual:");
        jPanel1.add(AvatarActualStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 540, -1, -1));

        FightingTitle.setFont(new java.awt.Font("Montserrat", 1, 36)); // NOI18N
        FightingTitle.setForeground(new java.awt.Color(255, 255, 255));
        FightingTitle.setText("FIGHTING AREA");
        jPanel1.add(FightingTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, -1));
        jPanel1.add(RegularShowCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, -1));
        jPanel1.add(AvatarCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, -1, -1));

        fightingSquare.setText(".");
        jPanel1.add(fightingSquare, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, -1));

        fightingTitle4.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        fightingTitle4.setForeground(new java.awt.Color(255, 255, 255));
        fightingTitle4.setText("PersonajeID:");
        jPanel1.add(fightingTitle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, -1, -1));

        cartoonNetworkLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cartoonNetworkLogo.setText("cartoonNetworkLogo");
        jPanel1.add(cartoonNetworkLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, 90));

        nickelodeonLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nickelodeonLogo.setText("a..");
        jPanel1.add(nickelodeonLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 30, -1, -1));

        jLabel21.setText("jLabel21");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 450, -1, -1));

        jLabel22.setText("jLabel21");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 500, -1, -1));

        jLabel23.setText("jLabel21");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, -1, -1));

        jLabel24.setText("jLabel21");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSlider1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jSlider1MouseClicked

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        // TODO add your handling code here:
        int newSpeed = jSlider1.getValue();
        app.getIaArena().setCombatSpeed(newSpeed);
    }//GEN-LAST:event_jSlider1StateChanged

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AvatarActualHP;
    private javax.swing.JLabel AvatarActualStatus;
    private javax.swing.JLabel AvatarCard;
    private javax.swing.JLabel AvatarCharacterID;
    private javax.swing.JLabel FightingTitle;
    private javax.swing.JLabel RegularShowActualHP;
    private javax.swing.JLabel RegularShowActualStatus;
    private javax.swing.JLabel RegularShowCard;
    private javax.swing.JLabel RegularShowCharacterID1;
    private javax.swing.JLabel Winner;
    private javax.swing.JLabel cartoonNetworkLogo;
    private javax.swing.JLabel fightingSquare;
    private javax.swing.JLabel fightingTitle4;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel nickelodeonLogo;
    // End of variables declaration//GEN-END:variables

    
    


}
