/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUIClasses;

import MainClasses.TelevisionShow;

/**
 *
 * @author angel
 */
public class TvPanelUI extends javax.swing.JPanel {

    /**
     * Creates new form TvPanelUI
     */
    public TvPanelUI() {
        initComponents();
    }
    
    public TvPanelUI(String logoUrl, TelevisionShow tv) {
        initComponents();
        
        this.getQueueUI1().updateQueueUI(tv.get);
        
        
        
        
        
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cartoonNetworkLogo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        queueUI1 = new GUIClasses.QueueUI();
        queueUI2 = new GUIClasses.QueueUI();
        queueUI3 = new GUIClasses.QueueUI();
        cartoonNetworkLogo1 = new javax.swing.JLabel();
        queueUI4 = new GUIClasses.QueueUI();

        cartoonNetworkLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cartoonNetworkLogo.setText("cartoonNetworkLogo");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(queueUI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        jPanel1.add(queueUI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));
        jPanel1.add(queueUI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

        cartoonNetworkLogo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cartoonNetworkLogo1.setText("TVLogo");
        jPanel1.add(cartoonNetworkLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 370, 90));
        jPanel1.add(queueUI4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 780));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cartoonNetworkLogo;
    private javax.swing.JLabel cartoonNetworkLogo1;
    private javax.swing.JPanel jPanel1;
    private GUIClasses.QueueUI queueUI1;
    private GUIClasses.QueueUI queueUI2;
    private GUIClasses.QueueUI queueUI3;
    private GUIClasses.QueueUI queueUI4;
    // End of variables declaration//GEN-END:variables

    public QueueUI getQueueUI1() {
        return this.queueUI1;
    }
    
    public QueueUI getQueueUI2() {
        return this.queueUI2;
    }
    
    public QueueUI getQueueUI3() {
        return this.queueUI3;
    }
    
    public QueueUI getQueueUI4() {
        return this.queueUI4;
    }
    
    public void addUICard(int priority, String urlCard) {
        
        
        
    }



}
